apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: https://github.com/Loukakou13/HomeLab.git
      targetRevision: main
      path: gitops/apps/sonarr
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sonarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        gateway-nginx-int-pub: true
    syncOptions:
      - CreateNamespace=true
