global:
  envFrom:
    - secretRef:
        name: authentik-secrets

authentik:
  postgresql:
    host: pg-cluster-rw.postgresql.svc.cluster.local
    name: authentik

server:
  route:
    main:
      enabled: true
      hostnames:
        - authentik.loukawai.fr
      parentRefs:
        - name: nginx-ext-pub
          namespace: gateway-system

postgresql:
  enabled: false

redis:
  enabled: false
