k3s_node_role: "agent"

k3s_w__firewall_rules:
  - { port: 8472, proto: 'udp', comment: 'k3s Flannel VXLAN' }
  - { from: 10.42.0.0/16, comment: 'k3s pods network' }
  - { from: 10.43.0.0/16, comment: 'k3s services network' }
  - { port: 80, proto: 'tcp', comment: 'http for ingress-nginx'}
  - { port: 443, proto: 'tcp', comment: 'https for ingress-nginx'}
