apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
              name: http
          env:
            - name: TZ
              value: "Europe/Paris"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /shows
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: shows
          nfs:
            server: 192.168.1.39
            path: /volume1/HomeLab-NFS/media/shows
        - name: downloads
          nfs:
            server: 192.168.1.39
            path: /volume1/HomeLab-NFS/media/downloads
