apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-media-shows
spec:
  storageClassName: "nfs-media"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-media-shows-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-media-downloads
spec:
  storageClassName: "nfs-media"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-media-downloads-nfs
