apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://github.com/Loukakou13/HomeLab.git
      targetRevision: feat/k8s-monitoring
      path: gitops/platform/kube-prometheus-stack
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 83.4.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/gitops/platform/kube-prometheus-stack/values.yml
    - repoURL: https://github.com/Loukakou13/HomeLab.git
      targetRevision: feat/k8s-monitoring
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        gateway-nginx-int-priv: "true"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
