apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: recyclarr-secrets
  namespace: recyclarr
spec:
  vaultAuthRef: recyclarr
  mount: infra
  type: kv-v2
  path: k8s/recyclarr/api_keys
  refreshAfter: 1h
  destination:
    create: true
    overwrite: true
    name: recyclarr-secrets
    type: Opaque
