- name: Restart unmanaged Pods by cilium
  ansible.builtin.shell: |
    set -o pipefail
    kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork --no-headers=true |
    grep '<none>' |
    awk '{print "-n "$1" "$2}' |
    xargs -L 1 -r kubectl delete pod
  register: cilium_restart
  changed_when: "'deleted' in cilium_restart.stdout"
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
