- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Configure fail2ban
  ansible.builtin.template:
    src: fail2ban_jail.local.j2
    dest: /etc/fail2ban/jail.d/{{ item.name }}.local
    owner: root
    group: root
    mode: '0644'
  loop: "{{ fail2ban_jails }}"
  notify: Restart fail2ban service

- name: Ensure fail2ban service is enabled and started
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
