- name: Check if server private key exists
  become: true
  ansible.builtin.stat:
    path: "{{ wireguard_config_dir }}/server_private.key"
  register: wireguard_server_private_key_stat

- name: Generate server private key
  ansible.builtin.command: wg genkey
  register: wireguard_server_private_key_cmd
  changed_when: false
  when: not wireguard_server_private_key_stat.stat.exists

- name: Save server private key
  become: true
  ansible.builtin.copy:
    content: "{{ wireguard_server_private_key_cmd.stdout }}"
    dest: "{{ wireguard_config_dir }}/server_private.key"
    mode: '0600'
  when: wireguard_server_private_key_cmd.stdout is defined

- name: Read server private key
  become: true
  ansible.builtin.slurp:
    src: "{{ wireguard_config_dir }}/server_private.key"
  register: wireguard_server_private_key_raw

- name: Decode server private key
  ansible.builtin.set_fact:
    wireguard_server_private_key: "{{ wireguard_server_private_key_raw.content | b64decode }}"

- name: Generate server public key
  ansible.builtin.shell: "echo {{ wireguard_server_private_key }} | wg pubkey"
  register: wireguard_server_public_key
  changed_when: false

- name: Clients side configurations
  ansible.builtin.import_tasks: clients.yml

- name: Template server config
  become: true
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: "{{ wireguard_config_dir }}/{{ wireguard_interface }}.conf"
    mode: '0600'
  notify: Restart wireguard
