apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: image-latest-tag
spec:
  validationActions:
    - Warn
    - Audit
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - message: Pods should not use latest tag image.
      expression: 'object.spec.containers.all(container, container.image.endsWith(":latest"))'
