- name: Donwload and run k3s installation script
  ansible.builtin.shell: "curl -sfL {{ k3s_script_url }} | sh -"

- name: Retrieve k3s node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_cluster_token

- name: Fetch kubeconfig file
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/
    flat: yes
