- name: Check if k3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Download the k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'
  when: not k3s_binary.stat.exists

- name: Run k3s install script with flags
  ansible.builtin.command:
    cmd: >
      /tmp/k3s-install.sh server
      --cluster-init
      --tls-san {{ k3s_vip }}
      --disable-cloud-controller
      --disable traefik
      --disable servicelb
      --flannel-backend='none'
      --disable-network-policy
  args:
    creates: /usr/local/bin/k3s
  become: true
  when: not k3s_binary.stat.exists

- name: Ensure the k3s service is running and enabled
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true

- name: Retrieve k3s node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_cluster_token

- name: Fetch kubeconfig file
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/k3s.yml
    flat: true

- name: Replace IPv4 in fetched kubeconfig file
  ansible.builtin.replace:
    path: /tmp/k3s.yml
    regexp: '127\.0\.0\.1'
    replace: '{{ ansible_host }}'
  delegate_to: localhost
  become: false
