- name: Donwload and run k3s installation script
  ansible.builtin.shell: "curl -sfL {{ k3s_script_url }} | sh -s - server --cluster-init --tls-san {{ k3s_vip }} {{ k3s_server_options }}"

- name: Retrieve k3s node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_cluster_token

- name: Fetch kubeconfig file
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/k3s.yml
    flat: yes

- name: Modifier l'adresse dans le kubeconfig
  ansible.builtin.replace:
    path: /tmp/k3s.yml
    regexp: '127\.0\.0\.1'
    replace: '{{ k3s_vip }}'
  delegate_to: localhost
  become: false
