- name: Donwload and run k3s installation script
  ansible.builtin.shell: "curl -sfL {{ k3s_script_url }} | K3S_URL=https://{{ hostvars[k3s_init_master]['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars[k3s_init_master]['k3s_cluster_token']['content'] | b64decode | trim }} sh -"
