- name: Check if k3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Download the k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'
  when: not k3s_binary.stat.exists

- name: Config firewall for K3s
  ansible.builtin.include_role:
    name: firewall
  vars:
    firewall_extra_rules:
      - { port: 6443, proto: tcp, comment: 'K3s API' }
      - { port: 8472, proto: udp, comment: 'Flannel VXLAN' }
      - { port: 2379:2380, proto: tcp, comment: 'HA with embedded etcd' }
      - { from: 10.42.0.0/16, comment: 'pods'}
      - { from: 10.43.0.0/16, comment: 'services' }

- name: Run k3s install script with flags
  ansible.builtin.command:
    cmd: >
      /tmp/k3s-install.sh {{ k3s_node_role }}
      --server https://{{ k3s_vip }}:6443
      --token {{ hostvars[k3s_init_master]['k3s_cluster_token']['content'] | b64decode | trim }}
      {{ '--disable traefik' if k3s_node_role == 'server' and not k3s_enable_traefik else '' }}
      {{ '--disable servicelb' if k3s_node_role == 'server' and not k3s_enable_servicelb else '' }}
  args:
    creates: /usr/local/bin/k3s
  become: true
  when: not k3s_binary.stat.exists

- name: Ensure the k3s service is running and enabled
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true
