- name: Donwload and run k3s installation script
  ansible.builtin.shell: "curl -sfL {{ k3s_script_url }} | K3S_TOKEN={{ hostvars[k3s_init_master]['k3s_cluster_token']['content'] | b64decode | trim }} sh -s - {{ k3s_node_role }} --server https://{{ k3s_vip }}:6443 {{ k3s_node_role == 'server' if k3s_server_options else '' }}"
