- name: Join the cluster
  ansible.builtin.include_tasks: prerequisites.yml

- name: Init the cluster
  ansible.builtin.include_tasks: init.yml
  when: k3s_init_master == ansible_hostname

- name: Join the cluster
  ansible.builtin.include_tasks: join.yml
  when: k3s_init_master != ansible_hostname
