- name: Configure UFW to allow k3s api server port
  community.general.ufw:
    rule: allow
    port: 6443
    proto: tcp

- name: Configure UFW to allow k3s pods
  community.general.ufw:
    rule: allow
    src: 10.42.0.0/16

- name: Configure UFW to allow k3s services
  community.general.ufw:
    rule: allow
    src: 10.43.0.0/16
