- name: Apply firewall rules
  community.general.ufw:
    rule: "{{ rule.rule | default('allow') }}"
    port: "{{ rule.port | default(omit) }}"
    proto: "{{ rule.proto | default(omit) }}"
    src: "{{ rule.src | default(omit) }}"
    from_ip: "{{ rule.from_ip | default('0.0.0.0/0') }}"
    to_ip: "{{ rule.to_ip | default(omit) }}"
    direction: "{{ rule.direction | default(omit) }}"
    interface: "{{ rule.interface | default(omit) }}"
    comment: "{{ rule.comment | default(omit) }}"
  when: rule.when | default(true)
