apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: Monitoring
  namespace: argocd
spec:
  description: Monitoring components
  sourceRepos:
    - https://github.com/ton-org/gitops-repo.git
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
