apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: applications
  sources:
    - repoURL: https://github.com/Loukakou13/HomeLab.git
      targetRevision: main
      path: gitops/manifests/authentik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
