apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  project: applications
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 21.1.22
    helm:
      releaseName: nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
