apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: applications
  sources:
    - repoURL: https://github.com/Loukakou13/HomeLab.git
      targetRevision: netbird
      path: gitops/manifests/netbird
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netbird
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
