apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: applications
  sources:
    - repoURL: https://github.com/Loukakou13/HomeLab.git
      targetRevision: main
      path: gitops/manifests/postgresql
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
