apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-ddns-secrets
  namespace: cloudflare-ddns
spec:
  vaultAuthRef: cloudflare-ddns
  mount: infra
  type: kv-v2
  path: k8s/cloudflare-ddns/secrets
  refreshAfter: 1h
  destination:
    create: true
    overwrite: true
    name: cloudflare-ddns-secrets
    type: Opaque
