- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Config firewall for keepalived
  ansible.builtin.include_role:
    name: firewall
    tasks_from: apply_rules.yml
  vars:
    firewall_extra_rules: "{{ keepalived_firewall_rules }}"

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart keepalived
  when: k3s_node_role == "server"
  vars:
    keepalived_priority: "{{ keepalived_base_priority - (inventory_hostname | regex_search('\\d+$') | int * 10) }}"

- name: Ensure the keepalived is running correctly
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: started
  when: k3s_node_role == "server"
