- name: Install Argo CD using Helm
  kubernetes.core.helm:
    name: argocd
    chart_repo_url: https://argoproj.github.io/argo-helm
    chart_ref: argo-cd
    chart_version: 9.4.17
    release_namespace: argocd
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    values_files:
      - "{{ role_path }}/files/values.yml"

- name: Download Argo CD root App manifest
  ansible.builtin.get_url:
    url: "{{ argocd_root_app_url }}"
    dest: /tmp/argocd-root.yml
    mode: '0664'

- name: Apply Argo CD root App manifest
  kubernetes.core.k8s:
    state: present
    src: /tmp/argocd-root.yml
