apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qbittorrent

resources:
  - deployment.yml
  - http-route.yml
  - pvc-config.yml
  - service-account.yml
  - service.yml
  - vault-auth.yml
  - vault-static-secret.yml
