apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gluetun-secrets
  namespace: qbittorrent
spec:
  vaultAuthRef: qbittorrent
  mount: infra
  type: kv-v2
  path: k8s/qbittorrent/gluetun
  refreshAfter: 1h
  destination:
    create: true
    overwrite: true
    name: gluetun-secrets
    type: Opaque
