- name: Install rsyslog
  ansible.builtin.package:
    name: rsyslog
    state: present

- name: Ensure rsyslog service is enabled and started
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
