apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
  namespace: argocd
spec:
  project: default
  source:
    chart: homarr
    repoURL: https://homarr-labs.github.io/charts/
    targetRevision: 5.8.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
