apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.30.1
    - repoURL: https://github.com/Loukakou13/HomeLab
      targetRevision: main
      ref: values
      path: argocd/values/vault
  source:
    helm:
      releaseName: vault
      valueFiles:
        - $values/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
