apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  project: applications
  sources:
    - chart: coredns
      repoURL: https://coredns.github.io/helm
      targetRevision: 1.45.0
      helm:
        releaseName: coredns
        valueFiles:
          - $values/gitops/manifests/coredns/values.yml
    - repoURL: https://github.com/Loukakou13/HomeLab.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coredns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
