apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-system

resources:
  - certificate.yml
  - gateway-nginx-ext-pub.yml
  - gateway-nginx-int-pub.yml
  - gateway-nginx-int-priv.yml
  - http-route-redirect-http-to-https.yml
