apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-system

resources:
  - namespace.yml
  - certificate.yml
  - gateway-external-nginx.yml
  - gateway-internal-nginx.yml
